services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: respectudental_app_t
    restart: unless-stopped
    ports:
      - "0.0.0.0:3311:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./tmp:/app/tmp
      # Don't mount public in production - it's already in the image
      # - ./public:/app/public
    command: sh -c "node server.js"