services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: respectudental_app_t
    restart: unless-stopped
    ports:
      - "0.0.0.0:3311:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    # volumes:
      # Don't mount tmp - let Docker create it with correct permissions
      # - ./tmp:/app/tmp
    command: sh -c "node server.js"